./contents/img/Comm_Diagram_-_Upload_Statement.png: ../requirements/dia/Comm_Diagram_-_Upload_Statement.dia
	dia --export=./contents/img/Comm_Diagram_-_Upload_Statement.png --filter=png ../requirements/dia/Comm_Diagram_-_Upload_Statement.dia

./contents/img/Comm_Diagram_-_Manual_Entry.png: ../requirements/dia/Comm_Diagram_-_Manual_Entry.dia
	dia --export=./contents/img/Comm_Diagram_-_Manual_Entry.png --filter=png ../requirements/dia/Comm_Diagram_-_Manual_Entry.dia

./contents/img/Comm_Diagram_-_Visualise_Categorised_Summary.png: ../requirements/dia/Comm_Diagram_-_Visualise_Categorised_Summary.dia
	dia --export=./contents/img/Comm_Diagram_-_Visualise_Categorised_Summary.png --filter=png ../requirements/dia/Comm_Diagram_-_Visualise_Categorised_Summary.dia

./contents/img/Comm_Diagram_-_Calculate_Budget.png: ../requirements/dia/Comm_Diagram_-_Calculate_Budget.dia
	dia --export=./contents/img/Comm_Diagram_-_Calculate_Budget.png --filter=png ../requirements/dia/Comm_Diagram_-_Calculate_Budget.dia

./contents/img/Comm_Diagram_-_Estimate_Tax.png: ../requirements/dia/Comm_Diagram_-_Estimate_Tax.dia
	dia --export=./contents/img/Comm_Diagram_-_Estimate_Tax.png --filter=png ../requirements/dia/Comm_Diagram_-_Estimate_Tax.dia



./contents/img/Class_Diagram_-_Transaction.png: ../requirements/dia/Class_Diagram_-_Transaction.dia
	dia --export=./contents/img/Class_Diagram_-_Transaction.png --filter=png ../requirements/dia/Class_Diagram_-_Transaction.dia

./contents/img/Activity_Diagram_-_Categorise_Entries.png: ../requirements/dia/Activity_Diagram_-_Categorise_Entries.dia
	dia --export=./contents/img/Activity_Diagram_-_Categorise_Entries.png --filter=png ../requirements/dia/Activity_Diagram_-_Categorise_Entries.dia

./contents/img/Class_Diagram_-_Categories_and_Amount.png: ../requirements/dia/Class_Diagram_-_Categories_and_Amount.dia
	dia --export=./contents/img/Class_Diagram_-_Categories_and_Amount.png --filter=png ../requirements/dia/Class_Diagram_-_Categories_and_Amount.dia

./contents/img/Class_Diagram_-_Summary_Category.png: ../requirements/dia/Class_Diagram_-_Summary_Category.dia
	dia --export=./contents/img/Class_Diagram_-_Summary_Category.png --filter=png ../requirements/dia/Class_Diagram_-_Summary_Category.dia

./contents/img/Class_Diagram_-_Memo_Categories_and_Posting_Rule.png: ../requirements/dia/Class_Diagram_-_Memo_Categories_and_Posting_Rule.dia
	dia --export=./contents/img/Class_Diagram_-_Memo_Categories_and_Posting_Rule.png --filter=png ../requirements/dia/Class_Diagram_-_Memo_Categories_and_Posting_Rule.dia

./contents/img/Class_Diagram_-_All_Classes.png: ../requirements/dia/Class_Diagram_-_All_Classes.dia
	dia --export=./contents/img/Class_Diagram_-_All_Classes.png --filter=png ../requirements/dia/Class_Diagram_-_All_Classes.dia



./contents/img/Activity_Diagram_-_Manual_Entry.png: ../requirements/dia/Activity_Diagram_-_Manual_Entry.dia 
	dia --export=./contents/img/Activity_Diagram_-_Manual_Entry.png --filter=png ../requirements/dia/Activity_Diagram_-_Manual_Entry.dia 

./contents/img/Use_Case_Diagram.png: ../requirements/dia/Use_Case_Diagram.dia 
	dia --export=./contents/img/Use_Case_Diagram.png --filter=png ../requirements/dia/Use_Case_Diagram.dia 




pdf:	report.tex ./contents/img/Activity_Diagram_-_Categorise_Entries.png ./contents/img/Activity_Diagram_-_Manual_Entry.png ./contents/img/Use_Case_Diagram.png ./contents/img/Class_Diagram_-_Categories_and_Amount.png ./contents/img/Class_Diagram_-_Transaction.png ./contents/img/Class_Diagram_-_Memo_Categories_and_Posting_Rule.png ./contents/img/Class_Diagram_-_All_Classes.png ./contents/img/Class_Diagram_-_Summary_Category.png ./contents/img/Comm_Diagram_-_Manual_Entry.png ./contents/img/Comm_Diagram_-_Upload_Statement.png ./contents/img/Comm_Diagram_-_Visualise_Categorised_Summary.png ./contents/img/Comm_Diagram_-_Calculate_Budget.png ./contents/img/Comm_Diagram_-_Estimate_Tax.png
	pdflatex report && biber report && pdflatex report && pdflatex report && mv report.pdf ../
